name: Storybook
on:
  pull_request:
    paths:
      - 'apps/storybook/**'
      - '.github/workflows/storybook.yml'
jobs:
  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - name: Build Storybook
        run: pnpm --filter ./apps/storybook... build
